apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: workload01-database-secrets
  namespace: workload01
spec:
  secretStoreRef:
    name: containscloud-lab-store
    kind: SecretStore
  # Get the secrets from AWS Secrets Manager
  dataFrom:
  - extract:
      key: containscloud-lab-secret
      conversionStrategy: Default
      decodingStrategy: Auto
    ## Rewrite the secret name to remove the prefix sqldb_
    rewrite:
    - regexp:
        source: ^sqldb_
        target: ""
  ## Interval to refresh the secret
  refreshInterval: 60s
  target:
    name: workload01-database
    creationPolicy: Owner
    deletionPolicy: Retain
